name: Trigger on JSON File Changes and Install Ansible

on:
  push:
    paths:
      - '**/*.json' # Trigger when any JSON file is created or updated
  pull_request:
    paths:
      - '**/*.json' # Trigger for pull requests involving JSON file changes

jobs:
  jsonFileChanges:
    runs-on: ubuntu-latest # Ensures the job runs on AMD64 architecture with an Ubuntu-based environment

    steps:
      # Step 1: Confirm Runner Architecture
      - name: Check Runner Architecture
        run: |
          echo "Runner OS: $(uname -s)"
          echo "Runner Architecture: $(uname -m)"
        # Expected output for architecture is "x86_64" (AMD64)

      # Step 2: Checkout repository to get the latest code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Set up Python (required to install Ansible)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify Python version (compatible for Ansible installation)

      # Step 4: Install Ansible
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip # Upgrade pip
          pip install ansible # Install Ansible
          ansible --version # Verify Ansible installation

      # Step 5: Custom Tasks Related to JSON Files
      - name: Handle JSON Changes
        run: |
          echo "Changes detected in JSON files!"
          echo "Running JSON-specific tasks..."